export const LeagesByCountry = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(
        {
          api: {
            results: {
              leagues: [
                {
                  'league_id': 2,
                  'name': 'Premier League',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-08-10',
                  'season_end': '2019-05-12',
                  'logo': 'https://media.api-football.com/leagues/2.png',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                },
                {
                  'league_id': 3,
                  'name': 'Championship',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-08-03',
                  'season_end': '2019-05-27',
                  'logo': 'https://media.api-football.com/leagues/3.png',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                },
                {
                  'league_id': 164,
                  'name': 'League One',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-08-04',
                  'season_end': '2019-05-26',
                  'logo': 'https://media.api-football.com/leagues/164.png',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                },
                {
                  'league_id': 167,
                  'name': 'League Two',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-08-04',
                  'season_end': '2019-05-25',
                  'logo': 'https://media.api-football.com/leagues/167.png',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                },
                {
                  'league_id': 222,
                  'name': 'National League',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-08-04',
                  'season_end': '2019-04-27',
                  'logo': 'https://media.api-football.com/leagues/222.png',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                },
                {
                  'league_id': 225,
                  'name': 'FA WSL',
                  'type': 'League',
                  'country': 'England',
                  'country_code': 'GB',
                  'season': 2018,
                  'season_start': '2018-09-09',
                  'season_end': '2019-05-11',
                  'logo': 'https://media.api-football.com/leagues/225.jpg',
                  'flag': 'https://media.api-football.com/flags/gb.svg',
                  'standings': 1,
                  'is_current': 0,
                }
              ]
            }
          }
        }
      )
    }, 1000)
  })
}

export const todayFixtures = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(
        {
          api: {
            results: {
              fixtures: [
                {
                  'fixture_id': 310830,
                  'league_id': 586,
                  'league': {
                    'name': 'Liga Nacional',
                    'country': 'Guatemala',
                    'logo': 'https://media.api-sports.io/football/leagues/339.png',
                    'flag': 'https://media.api-sports.io/flags/gt.svg',
                  },
                  'event_timestamp': 1580947200,
                  'firstHalfStart': 1580947200,
                  'secondHalfStart': 1580950800,
                  'round': 'Clausura - 5',
                  'status': 'Not Started',
                  'statusShort': 'NS',
                  'elapsed': 90,
                  'venue': 'Estadio Armando Barillas (Escuintla)',
                  'referee': 'M. Escobar',
                  'homeTeam': {
                    'team_id': 3666,
                    'team_name': 'Siquinalá',
                    'logo': 'https://media.api-sports.io/football/teams/3666.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 2,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 293267,
                  'league_id': 1250,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Atanasio Girardot (Medellín)',
                  'referee': 'Anderson Daronco, Brazil',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 445,
                    'team_name': 'Huracan',
                    'logo': 'https://media.api-sports.io/football/teams/445.png',
                  },
                  'goalsHomeTeam': 3,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 313561,
                  'league_id': 875,
                  'league': {
                    'name': 'Copa Do Brasil',
                    'country': 'Brazil',
                    'logo': 'https://media.api-sports.io/football/leagues/73.png',
                    'flag': 'https://media.api-sports.io/flags/br.svg',
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': 'Clausura - 5',
                  'status': 'Not Started',
                  'statusShort': 'NS',
                  'elapsed': 90,
                  'venue': 'Estadio Jose Gregorio Martínez (Chalatenango)',
                  'referee': 'W. García',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 315777,
                  'league_id': 1333,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Arena Pantanal (Cuiabá, Mato Grosso)',
                  'referee': 'Ivan da Silva Guimarães Junior',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 315781,
                  'league_id': 1333,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estádio Municipal Nílton Santos (Palmas, Tocantins)',
                  'referee': 'Marco Aurelio Augusto Fazekas Pereira',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 2,
                },
                {
                  'fixture_id': 315787,
                  'league_id': 1333,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Not Started',
                  'statusShort': 'NS',
                  'elapsed': 90,
                  'venue': 'Estádio Governador Alberto Tavares Silva (Teresina, Piauí)',
                  'referee': 'Jefferson Ferreira de Moraes',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 315788,
                  'league_id': 1333,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Not Started',
                  'statusShort': 'NS',
                  'elapsed': 90,
                  'venue': 'Estádio Francisco Stédile (Caxias do Sul, Rio Grande do Sul)',
                  'referee': 'Lucas Canetto Bellote',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 315790,
                  'league_id': 1333,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estádio da Noroeste (Aquidauana, Mato Grosso do Sul)',
                  'referee': 'Charly Wendy Straub Deretti',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 315946,
                  'league_id': 1251,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '2nd Round',
                  'status': 'Not Started',
                  'statusShort': 'NS',
                  'elapsed': 90,
                  'venue': 'Estadio Hernando Siles (La Paz)',
                  'referee': 'G. Guerrero',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 2,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 321813,
                  'league_id': 1250,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '1st Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estádio Club de Regatas Vasco da Gama (Rio de Janeiro, Rio de Janeiro)',
                  'referee': 'Augusto Bergelio Aragon Bautista, Ecuador',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 321826,
                  'league_id': 1251,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:30:00+00:00',
                  'event_timestamp': 1580949000,
                  'firstHalfStart': 1580949000,
                  'secondHalfStart': 1580952600,
                  'round': '2nd Round',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio General Pablo Rojas (Asunción)',
                  'referee': 'A. Herrera',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 0,
                },
                {
                  'fixture_id': 314401,
                  'league_id': 1327,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T00:40:00+00:00',
                  'event_timestamp': 1580949600,
                  'firstHalfStart': 1580949600,
                  'secondHalfStart': 1580953200,
                  'round': 'Apertura - 1',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Guillermo Plazas Alcid (Neiva)',
                  'referee': 'S. Camargo',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 310829,
                  'league_id': 586,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 5',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Verapaz Jose Angel Rossi (Cobán)',
                  'referee': 'B. Castellanos',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 2,
                },
                {
                  'fixture_id': 310832,
                  'league_id': 586,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 5',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Santo Domingo (Mixco)',
                  'referee': 'J. Luna',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 5,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 313097,
                  'league_id': 588,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 7',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Ebal Rodríguez Aguilar (Guápiles)',
                  'referee': 'B. Pineda',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 5,
                  'goalsAwayTeam': 2,
                },
                {
                  'fixture_id': 320911,
                  'league_id': 785,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 3',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Solidaridad Augusto Cesar Mendoza (Somoto)',
                  'referee': 'R. Hernandez',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 1,
                  'goalsAwayTeam': 2,
                },
                {
                  'fixture_id': 320912,
                  'league_id': 785,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 3',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Roy Fernando Bermúdez (Ocotal)',
                  'referee': 'W. Barrientos',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 0,
                  'goalsAwayTeam': 1,
                },
                {
                  'fixture_id': 320913,
                  'league_id': 785,
                  'league': {
                    'name': 'CONMEBOL Sudamericana',
                    'country': 'World',
                    'logo': 'https://media.api-sports.io/football/leagues/11.png',
                    'flag': null,
                  },
                  'event_date': '2020-02-06T01:00:00+00:00',
                  'event_timestamp': 1580950800,
                  'firstHalfStart': 1580950800,
                  'secondHalfStart': 1580954400,
                  'round': 'Clausura - 3',
                  'status': 'Match Finished',
                  'statusShort': 'FT',
                  'elapsed': 90,
                  'venue': 'Estadio Cacique Diriangén (Diriamba)',
                  'referee': 'N. Sandoval',
                  'homeTeam': {
                    'team_id': 1137,
                    'team_name': 'Atletico Nacional',
                    'logo': 'https://media.api-sports.io/football/teams/1137.png',
                  },
                  'awayTeam': {
                    'team_id': 3662,
                    'team_name': 'Guastatoya',
                    'logo': 'https://media.api-sports.io/football/teams/3662.png',
                  },
                  'goalsHomeTeam': 2,
                  'goalsAwayTeam': 0,
                }
              ]
            }
          }
        }
      )
    }, 1000)
  })
}

export const leagueStatnding = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(
        {
          api: {
            results: {
              standings: [
                {
                  'rank': 1,
                  'team_id': 40,
                  'teamName': 'Liverpool',
                  'logo': 'https://media.api-sports.io/football/teams/40.png',
                  'group': 'Premier League',
                  'forme': 'WLWWW',
                  'status': 'same',
                  'description': 'Promotion - Champions League (Group Stage)',
                  'all': {
                    'matchsPlayed': 29,
                    'win': 27,
                    'draw': 1,
                    'lose': 1,
                    'goalsFor': 66,
                    'goalsAgainst': 21,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 15,
                    'draw': 0,
                    'lose': 0,
                    'goalsFor': 40,
                    'goalsAgainst': 12,
                  },
                  'away': {
                    'matchsPlayed': 14,
                    'win': 12,
                    'draw': 1,
                    'lose': 1,
                    'goalsFor': 26,
                    'goalsAgainst': 9,
                  },
                  'goalsDiff': 45,
                  'points': 82,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 2,
                  'team_id': 50,
                  'teamName': 'Manchester City',
                  'logo': 'https://media.api-sports.io/football/teams/50.png',
                  'group': 'Premier League',
                  'forme': 'LWWLW',
                  'status': 'same',
                  'description': 'Promotion - Champions League (Group Stage)',
                  'all': {
                    'matchsPlayed': 28,
                    'win': 18,
                    'draw': 3,
                    'lose': 7,
                    'goalsFor': 68,
                    'goalsAgainst': 31,
                  },
                  'home': {
                    'matchsPlayed': 13,
                    'win': 9,
                    'draw': 2,
                    'lose': 2,
                    'goalsFor': 33,
                    'goalsAgainst': 12,
                  },
                  'away': {
                    'matchsPlayed': 15,
                    'win': 9,
                    'draw': 1,
                    'lose': 5,
                    'goalsFor': 35,
                    'goalsAgainst': 19,
                  },
                  'goalsDiff': 37,
                  'points': 57,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 3,
                  'team_id': 46,
                  'teamName': 'Leicester',
                  'logo': 'https://media.api-sports.io/football/teams/46.png',
                  'group': 'Premier League',
                  'forme': 'WLLDD',
                  'status': 'same',
                  'description': 'Promotion - Champions League (Group Stage)',
                  'all': {
                    'matchsPlayed': 29,
                    'win': 16,
                    'draw': 5,
                    'lose': 8,
                    'goalsFor': 58,
                    'goalsAgainst': 28,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 9,
                    'draw': 3,
                    'lose': 3,
                    'goalsFor': 30,
                    'goalsAgainst': 15,
                  },
                  'away': {
                    'matchsPlayed': 14,
                    'win': 7,
                    'draw': 2,
                    'lose': 5,
                    'goalsFor': 28,
                    'goalsAgainst': 13,
                  },
                  'goalsDiff': 30,
                  'points': 53,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 4,
                  'team_id': 49,
                  'teamName': 'Chelsea',
                  'logo': 'https://media.api-sports.io/football/teams/49.png',
                  'group': 'Premier League',
                  'forme': 'WDWLD',
                  'status': 'same',
                  'description': 'Promotion - Champions League (Group Stage)',
                  'all': {
                    'matchsPlayed': 29,
                    'win': 14,
                    'draw': 6,
                    'lose': 9,
                    'goalsFor': 51,
                    'goalsAgainst': 39,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 7,
                    'draw': 3,
                    'lose': 5,
                    'goalsFor': 22,
                    'goalsAgainst': 15,
                  },
                  'away': {
                    'matchsPlayed': 14,
                    'win': 7,
                    'draw': 3,
                    'lose': 4,
                    'goalsFor': 29,
                    'goalsAgainst': 24,
                  },
                  'goalsDiff': 12,
                  'points': 48,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 5,
                  'team_id': 33,
                  'teamName': 'Manchester United',
                  'logo': 'https://media.api-sports.io/football/teams/33.png',
                  'group': 'Premier League',
                  'forme': 'WDWWD',
                  'status': 'same',
                  'description': 'Promotion - Europa League (Group Stage)',
                  'all': {
                    'matchsPlayed': 29,
                    'win': 12,
                    'draw': 9,
                    'lose': 8,
                    'goalsFor': 44,
                    'goalsAgainst': 30,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 8,
                    'draw': 5,
                    'lose': 2,
                    'goalsFor': 29,
                    'goalsAgainst': 12,
                  },
                  'away': {
                    'matchsPlayed': 14,
                    'win': 4,
                    'draw': 4,
                    'lose': 6,
                    'goalsFor': 15,
                    'goalsAgainst': 18,
                  },
                  'goalsDiff': 14,
                  'points': 45,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 6,
                  'team_id': 39,
                  'teamName': 'Wolves',
                  'logo': 'https://media.api-sports.io/football/teams/39.png',
                  'group': 'Premier League',
                  'forme': 'DWWDD',
                  'status': 'same',
                  'description': null,
                  'all': {
                    'matchsPlayed': 29,
                    'win': 10,
                    'draw': 13,
                    'lose': 6,
                    'goalsFor': 41,
                    'goalsAgainst': 34,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 5,
                    'draw': 7,
                    'lose': 3,
                    'goalsFor': 21,
                    'goalsAgainst': 17,
                  },
                  'away': {
                    'matchsPlayed': 14,
                    'win': 5,
                    'draw': 6,
                    'lose': 3,
                    'goalsFor': 20,
                    'goalsAgainst': 17,
                  },
                  'goalsDiff': 7,
                  'points': 43,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 7,
                  'team_id': 62,
                  'teamName': 'Sheffield Utd',
                  'logo': 'https://media.api-sports.io/football/teams/62.png',
                  'group': 'Premier League',
                  'forme': 'WDWWL',
                  'status': 'same',
                  'description': null,
                  'all': {
                    'matchsPlayed': 28,
                    'win': 11,
                    'draw': 10,
                    'lose': 7,
                    'goalsFor': 30,
                    'goalsAgainst': 25,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 7,
                    'draw': 3,
                    'lose': 5,
                    'goalsFor': 17,
                    'goalsAgainst': 13,
                  },
                  'away': {
                    'matchsPlayed': 13,
                    'win': 4,
                    'draw': 7,
                    'lose': 2,
                    'goalsFor': 13,
                    'goalsAgainst': 12,
                  },
                  'goalsDiff': 5,
                  'points': 43,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 8,
                  'team_id': 47,
                  'teamName': 'Tottenham',
                  'logo': 'https://media.api-sports.io/football/teams/47.png',
                  'group': 'Premier League',
                  'forme': 'DLLWW',
                  'status': 'same',
                  'description': null,
                  'all': {
                    'matchsPlayed': 29,
                    'win': 11,
                    'draw': 8,
                    'lose': 10,
                    'goalsFor': 47,
                    'goalsAgainst': 40,
                  },
                  'home': {
                    'matchsPlayed': 14,
                    'win': 8,
                    'draw': 2,
                    'lose': 4,
                    'goalsFor': 27,
                    'goalsAgainst': 15,
                  },
                  'away': {
                    'matchsPlayed': 15,
                    'win': 3,
                    'draw': 6,
                    'lose': 6,
                    'goalsFor': 20,
                    'goalsAgainst': 25,
                  },
                  'goalsDiff': 7,
                  'points': 41,
                  'lastUpdate': '2020-04-06',
                },
                {
                  'rank': 9,
                  'team_id': 42,
                  'teamName': 'Arsenal',
                  'logo': 'https://media.api-sports.io/football/teams/42.png',
                  'group': 'Premier League',
                  'forme': 'WWWDD',
                  'status': 'same',
                  'description': null,
                  'all': {
                    'matchsPlayed': 28,
                    'win': 9,
                    'draw': 13,
                    'lose': 6,
                    'goalsFor': 40,
                    'goalsAgainst': 36,
                  },
                  'home': {
                    'matchsPlayed': 15,
                    'win': 7,
                    'draw': 5,
                    'lose': 3,
                    'goalsFor': 26,
                    'goalsAgainst': 20,
                  },
                  'away': {
                    'matchsPlayed': 13,
                    'win': 2,
                    'draw': 8,
                    'lose': 3,
                    'goalsFor': 14,
                    'goalsAgainst': 16,
                  },
                  'goalsDiff': 4,
                  'points': 40,
                  'lastUpdate': '2020-04-06',
                }
              ]
            }
          }
        }
      )
    }, 1000)
  })
}